sudo: required

services:
  - docker

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - docker pull blang/latex

script:
  - cd src/Expose && ../../build/dockercmd.sh /bin/sh -c "latexmk -f -pdf -xelatex -shell-escape -interaction=nonstopmode -halt-on-error main.tex"
  - cp main.pdf ../../Expose.pdf
  - cd ../Report && ../../build/dockercmd.sh /bin/sh -c "latexmk -f -pdf -xelatex -shell-escape -interaction=nonstopmode -halt-on-error main.tex"
  - cp main.pdf ../../OpenSource.pdf
  - cd ../..

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: K2SdBVUp3y6yVcxijEb/zP6RXj+vQxSRiKVm8zmjIZS/D8wMdR1xcBIQON4LJHb45KQmSOu3HvrhjjXde2T1HWOca3JVGlZBFOIMfpaQY03eaOL7Isorpz3erG/locTDayMYyldsBpjwK2s5ymDqhwoXXtfeoIMrC+LRQwwW6F+/ROVK6MbHrUV/xHqHnaPCTyvYPRhE9FQxO7THMDpnO/npZ1VqV5keRs136Z4bUFkujZ9VUydjIJz6AbuHP4SA/2w4f63QbaUL7MOqmXWYtemKPz8NjZr9aPsu+vWaDAbee8V0omq696BY+WGuLw+3shRPcpBJF9RiYcRv32xQhO9C4/6sdbbJnMm3EFf45Hh2O/VK6CVRlvBcNOFh75+TOCJcYI+/DGC5QIPGaps0SRfoJWkiCnp4I4lxwilSBVPrQl+AQ2390iNXbcickDLJGSR65QP9GKyfULzWoO6Nzg1oGV+1UyA6UoF2VeqxYvtS9iXQsV1gzaTCZ1bwTH0ll46eK66A1nRKBEztAwiWNHVZmb8ZZc74IEPyLgvqW5eN8y/riwWfBhUzviIyJnopjEMQM14s7AAfaA1exU0SLT9n7WY7E8WerKKzFiQAUl6P3rNDlWeFZIVhQM225ZTSKVn2OARRbBj57/7G1SmiZvpZRqT6BTHU23NHqtG+8QE=
  file:
    - Expose.pdf
    - OpenSource.pdf
  prerelease: true
  name: "CI Pre-release"
  body: "This pre-release was automatically issued by the CI-System triggered by the merge of a pull request. Note that there are no guarantees regarding quality or completeness of the document appended to this release since it was automatically built."
  on:
    repo: TexNAK/OpenSource
    branch: "master"
